version: "3.9"

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - "8080:8080"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=weather_tasks
      - POSTGRES_PASSWORD=weather_tasks
      - POSTGRES_DB=weather_tasks_dev
    env_file:
      - ./.env.dev
volumes:
  postgres_data:
