# Generated by Django 3.2.9 on 2021-11-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('nearest_city', models.CharField(max_length=50)),
                ('complete', models.BooleanField(default=False)),
                ('weather_colour', models.CharField(max_length=50)),
                ('temperature', models.FloatField(default=0)),
            ],
        ),
    ]
