cities = [
    'Andorra la Vella', 'Kabul', "St. John's", 'Tirana', 'Yerevan', 'Luanda', 'Buenos Aires', 'Vienna',
    'Canberra', 'Baku', 'Bridgetown', 'Dhaka', 'Brussels', 'Ouagadougou', 'Sofia', 'Manama', 'Bujumbura',
    'Porto-Novo', 'Bandar Seri Begawan', 'Sucre', 'BrasÃ\xadlia', 'Nassau', 'Thimphu', 'Gaborone',
    'Minsk', 'Belmopan', 'Ottawa', 'Kinshasa', 'Brazzaville', 'Yamoussoukro', 'Santiago', 'YaoundÃ©',
    'Beijing', 'BogotÃ¡', 'San JosÃ©', 'Havana', 'Praia', 'Nicosia', 'Prague', 'Berlin', 'Djibouti City',
    'Copenhagen', 'Roseau', 'Santo Domingo', 'Quito', 'Tallinn', 'Cairo', 'Asmara', 'Addis Ababa',
    'Helsinki', 'Suva', 'Paris', 'Libreville', 'Tbilisi', 'Accra', 'Banjul', 'Conakry', 'Athens',
    'Guatemala City', 'Port-au-Prince', 'Bissau', 'Georgetown', 'Tegucigalpa', 'Budapest', 'Jakarta',
    'Dublin', 'Jerusalem', 'New Delhi', 'Baghdad', 'Tehran', 'ReykjavÃ\xadk', 'Rome', 'Kingston', 'Amman',
    'Tokyo', 'Nairobi', 'Bishkek', 'Tarawa', 'Pyongyang', 'Seoul', 'Kuwait City', 'Beirut', 'Vaduz',
    'Monrovia', 'Maseru', 'Vilnius', 'Luxembourg City', 'Riga', 'Tripoli', 'Antananarivo', 'Majuro',
    'Skopje', 'Bamako', 'Naypyidaw', 'Ulaanbaatar', 'Nouakchott', 'Valletta', 'Port Louis', 'MalÃ©',
    'Lilongwe', 'Mexico City', 'Kuala Lumpur', 'Maputo', 'Windhoek', 'Niamey', 'Abuja', 'Managua',
    'Amsterdam', 'Oslo', 'Kathmandu', 'Yaren', 'Wellington', 'Muscat', 'Panama City', 'Lima',
    'Port Moresby', 'Manila', 'Islamabad', 'Warsaw', 'Lisbon', 'Ngerulmud', 'AsunciÃ³n', 'Doha',
    'Bucharest', 'Moscow', 'Kigali', 'Riyadh', 'Honiara', 'Victoria', 'Khartoum', 'Stockholm',
    'Singapore', 'Ljubljana', 'Bratislava', 'Freetown', 'San Marino', 'Dakar', 'Mogadishu', 'Paramaribo',
    'SÃ£o TomÃ©', 'Damascus', 'LomÃ©', 'Bangkok', 'Dushanbe', 'Ashgabat', 'Tunis', 'NukuÊ»alofa',
    'Ankara', 'Port of Spain', 'Funafuti', 'Dodoma', 'Kyiv', 'Kampala', 'Washington, D.C.', 'Montevideo',
    'Tashkent', 'Vatican City', 'Caracas', 'Hanoi', 'Port Vila', "Sana'a", 'Lusaka', 'Harare', 'Algiers',
    'Sarajevo', 'Phnom Penh', 'Bangui', "N'Djamena", 'Moroni', 'Zagreb', 'Dili', 'San Salvador', 'Malabo',
    "St. George's", 'Astana', 'Vientiane', 'Palikir', 'ChiÅ\x9finÄ\x83u', 'Monaco', 'Podgorica', 'Rabat',
    'Basseterre', 'Castries', 'Kingstown', 'Apia', 'Belgrade', 'Pretoria', 'Madrid',
    'Sri Jayewardenepura Kotte', 'Mbabane', 'Bern', 'Abu Dhabi', 'London'
]
