"""
Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from .allowed_hosts import *
from .apps import *
from .db import *
from .internationalization import *
from .middleware import *
from .password_validators import *
from .static_media import *
from .templates import *
from .vars import *
